#!/bin/sh
# Toggle keyboard layout between us and latam

current=$(setxkbmap -query | awk '/layout:/{print $2}')
if [ "$current" = "latam" ]; then
    setxkbmap -model pc105 -layout us
else
    setxkbmap -model pc105 -layout latam
fi
