; Polybar entrypoint
; Keep this file minimal and include modular config files.

include-file = ~/.config/polybar/conf/colors.ini
include-file = ~/.config/polybar/conf/global.ini
include-file = ~/.config/polybar/conf/bar.ini

include-file = ~/.config/polybar/conf/modules/workspaces.ini
include-file = ~/.config/polybar/conf/modules/xwindow.ini
include-file = ~/.config/polybar/conf/modules/cpu.ini
include-file = ~/.config/polybar/conf/modules/ram.ini
include-file = ~/.config/polybar/conf/modules/volume.ini
include-file = ~/.config/polybar/conf/modules/wifi.ini
include-file = ~/.config/polybar/conf/modules/battery.ini
include-file = ~/.config/polybar/conf/modules/date.ini
include-file = ~/.config/polybar/conf/modules/powermenu.ini
